### ISSUE TITLE
missing nugets?

### ISSUE THREAD

**Issue by circuitb** [vvvv/VL.RunwayML#1]
hello,
looks promising and straightforward! 
with vvvv_gamma_2020.2.0-0217-g78b13ed816
when i try to install the 2 missing nugets i've both
Unable to find package 'VL.RunwayML'
Unable to find package 'VL.Stride'
any hints?

**Comment by joreg** [comment]
ai circuit,

as mentioned in the readme, this requires a 2020.2 preview!

and also you still need to build this yourself locally first. 
when building in vs you'll need to add the vvvv nuget source:
http://teamcity.vvvv.org/guestAuth/app/nuget/v1/FeedService.svc/

**Comment by circuitb** [comment]
hey joreg,
thanks for the explanation
installing vvvv_gamma_2020.2.0-0202-ge5ff990162? or 2020.2 preview is it still a private release?

in the meantime trying to build the source in vs2019 i get this errors
using Stride.Core.Mathematics;

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Stride' could not be found (are you missing a using directive or an assembly reference?)	VL.RunwayML	G:\projects\_Packs\_VL\VL.RunwayML-master\src\ModelFactory.cs	19	N/A

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0738	'RunwayMLFactory' does not implement interface member 'IVLNodeDescriptionFactory.NodeDescriptions'. 'RunwayMLFactory.NodeDescriptions' cannot implement 'IVLNodeDescriptionFactory.NodeDescriptions' because it does not have the matching return type of 'ReadOnlyObservableCollection<IVLNodeDescription>'.	VL.RunwayML	G:\projects\_Packs\_VL\VL.RunwayML-master\src\ModelFactory.cs	26	N/A

**Comment by joreg** [comment]
vvvv_gamma_2020.2.0-0202-ge5ff990162 is a preview build, yes.

and re build errors: do you have the nuget source specified as mentioned above?

**Comment by circuitb** [comment]
yep
installed VL.Skia version is 2020.1.7

**Comment by circuitb** [comment]
> yep
> installed VL.Skia version is 2020.1.7

forgot to check : include prerelease i guess...

**Comment by circuitb** [comment]
everything works now thanks joreg
